### ISSUE TITLE
Some divergence from WebKitCSSMatrix

### ISSUE THREAD

**Issue by erykpiast** [jonbrennecke/CSSMatrix#1]
Is it problem only with perspective in demo?

http://codepen.io/jonbrennecke/pen/mvqab

![screenshot from 2014-01-22 10 17 17](https://f.cloud.github.com/assets/1434406/1972358/48768926-8347-11e3-8e3d-dff9466053a0.png)
![screenshot from 2014-01-22 10 17 41](https://f.cloud.github.com/assets/1434406/1972359/4dffa300-8347-11e3-89f0-f43b89700d0b.png)

**Comment by jonbrennecke** [comment]
Alright I think I fixed it!

It appears the WebKitCSSMatrix's toString() function truncates each number to 6 decimal places. I've implemented that and it appears to fix the issue. 

The difference on rotateY isn't divergence, but (I believe) mirroring due to the fact that 'perspective-origin' is pointed at the center of the containing element.

![image](https://f.cloud.github.com/assets/4308472/1980959/b503a22e-83cc-11e3-96d0-1c7e799d7e61.png)

![image](https://f.cloud.github.com/assets/4308472/1980937/35db04ba-83cc-11e3-80a4-49bb6d475c7c.png)
